### PR TITLE
Fix csh activate/deactivate code, add test suite

### PR DESCRIPTION
**Pull request by x0id**
# Description

The C shell kerl activate/deactivate code has been improved and refactored to fix environment setup/cleanup issues (https://github.com/kerl/kerl/issues/458).

The test suite for C shell based activate/deactivate code added.

This PR completes fixing the issue https://github.com/kerl/kerl/issues/458.

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/kerl/kerl/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for this, @x0id. I've linked #458. FYI, if you use words like "Closes ..." or similar (like in the template) the issue is auto-linked. Ref: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

I'll review now.

**Review by paulo-ferraz-oliveira — APPROVED** [review]
I'm not a C shell expert, but you get my approval.

The tests read as reasonable, and the changes follow what you did before.

5 ⭐

**Review by jadeallenx — APPROVED** [review]

**Comment by jadeallenx** [comment]
great! thank you

**Comment by paulo-ferraz-oliveira** [comment]
@jadeallenx, with this maybe we can cut a release? Or you wanna wait some more?

**Comment by jadeallenx** [comment]
> @jadeallenx, with this maybe we can cut a release? Or you wanna wait some more?

Since we merged #465 (a breaking change) I feel like we should get in the package detection change (if you are going to work on it?) before a new release. If you don't have time (which is fine, btw), then I will cut a new release.

**Comment by paulo-ferraz-oliveira** [comment]
Lemme try to go over the issue/thread and try to figure out an algo 👍 (no promises, though 😄)

**Pull request merged**
