### PR TITLE
ci-centos6: test centos6 + otp/20.2

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by mrallen1** [comment]
Pierre, meant to get to this sooner - I am sorry about the delay. We'd like to invite you to join the maintenance group - you've done a lot of great work for the project so we'd like you to join our team.  Hope you agree!

**Comment by fenollp** [comment]
Sorry just saw this. Sure I'll join! Do I need to click something special?

**Comment by mrallen1** [comment]
Yeah I sent you an invite to join the organization - click on that and get enrolled so I can update your permissions.

**Comment by fenollp** [comment]
Ah! Yes finally found that email sorry about that. So what do you Think if I merge this as well as the shellcheck PR? I rebased that one just today

**Comment by mrallen1** [comment]
See part of my not-so-evil plan here is that you will help be on the hook to help keep the shellcheck stuff up to date 😈 So merge away :)

**Pull request merged**
