### PR TITLE
Fix issue #88

### LINKED ISSUE #88: kerl prompt displays two versions
I've got 17.3 and 17.3.4 installed using kerl. I'm using 17.3, and `kerl prompt` returns

```
 (17.3
17.3.4)
```

I was expecting it to return only ` (17.3)`

### PR DESCRIPTION
**Pull request by mazenharake**
This should fix #88, I noticed though that this also affects the `do_deploy()` which *should* have had a problem but it hasn't been reported anywhere.

I've tested it. 

@rlipscombe / can you try verify?

### CODE REVIEW

**Comment by mazenharake** [comment]
Someone also needs to test this on FreeBSD but it "should work"tm

**Comment by mrallen1** [comment]
Need to test this out before I merge it, but it looks good so far.

**Comment by rlipscombe** [comment]
My apologies, I've not had a chance to try this yet. If @mrallen1 is happy with testing it, then I guess we're good. If not, let me know and I'll try to make some time later this week.

**Comment by mrallen1** [comment]
Pathological case here:

```
$ cat ~/.kerl/otp_installations
foo /tmp/test
bar /tmp/test
$ . /tmp/test/activate
$ kerl prompt
(foo
 bar)
```

How do you do this? You install `foo` into `/tmp/test`, then `rm -rf /tmp/test` and then install `bar` into the same location.  The installation check routine needs to make sure the installation location is not already present in our installation file before we allow an install.

**Comment by mrallen1** [comment]
Otherwise, this looks good.

**Comment by mazenharake** [comment]
Added the check to see if the installation path is already registered and also added `-m1` to the grep so that it always returns only 1 row (which *should* always be the only one).

**Comment by mrallen1** [comment]
Thanks! This looks great.

**Pull request merged**
