### PR TITLE
change default KERL_BUILD_BACKEND to "git" (from "tarball") after #274

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by mrallen1** [comment]
I am wary about making this change because it will break people who expect the tool to work "the way it always had."  The git build process imposes additional prereqs like autoconf, git, and automake that people might not have installed.

I think it would be better to set a date for the change over and then merge this work - like make an announcement that on/around June 1, 2018, we are going make this change, so if you have any automation that would be affected by this change, pin it to an older version of kerl or adjust the build process now.

**Comment by mrallen1** [comment]
I think it's time to reconsider this and make it the default. We'll bump the version tag and make an announcement to erlang-questions ahead of time.

**Comment by fenollp** [comment]
Rebased! Turns out the PR is even smaller now :)

I must have confused the hell out of these CIs cause I created & deleted the same branch on kerl/kerl instead of force-pushing on fenollp/kerl ;) 
So these should be false negatives.

**Comment by fenollp** [comment]
@mrallen1 I rebased but I think this uncovered a regression with OTP 17 on Trusty WRT wxwidgets: https://app.circleci.com/jobs/github/fenollp/kerl/473/parallel-runs/0/steps/0-105 Ideas?

**Comment by mrallen1** [comment]
I dunno - it says wxWidgets not found - not sure why that is.

**Comment by mrallen1** [comment]
My usual approach would be to see if there's a patch in OTP somewhere upstream that we could possibly adapt or incorporate.

**Comment by fenollp** [comment]
Nothing's changed except for the build backend, so maybe the things the OTP team does when releasing a tarball was not done for R17.0?

I could just drop Trusty as it is EOL by Canonical...

**Comment by mrallen1** [comment]
Any OS that's EOL'd upstream of us we should drop from our test matrix IMO

**Comment by fenollp** [comment]
Travis CI macOS builds seem to be failing due to https://pattern-match.com/blog/2019/01/27/erlang-how-to-safely-build-erlang-with-crypto-without-openssl-issues/ (the new openssl 1.1.x API).

**Comment by fenollp** [comment]
@mrallen1 What do you think about cutting a v2 from here?

**Comment by mrallen1** [comment]
Yeah seems like a good call to me. But like I said, I want to make an announcement at CodeBEAM and then we'll launch 2.0.0 with the switch to git builds as default

**Pull request merged**
