### PR TITLE
Prepare for OTP 27

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
# Description

This can/should be accepted/merged (only) when 27 is moved from release candidate status.

⚠️ ~Opening as draft to signal that.~
⚠️ ~On second thought, there's an actual "issue" that might need solving, which is to use `ex_doc` to generate local documentation from 27 on.~ (this has been addressed, next to OTP, by @garazdawi, as mentioned in the linked issue)

**Note**: I'll try to remember to leave this here up until 27 is released, and then I'll release. If anything important comes up or is merged, I'll rebase.

## Reference

* https://erlangforums.com/t/erlang-otp-27-0-rc1-released/3300

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/kerl/kerl/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Locally tested on macOS. Saw HTML documentation built with `ex_doc` while not having it present in the installation folder.

`find . -name ex_doc` yields no result in the installation target.

`which ex_doc` doesn't find `ex_doc`, either before or after `. ./activate`.

**Review by jadeallenx — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
@garazdawi, feel free to give this a quick look, as I might've missed a detail somewhere 👍 Thanks.

**Review by garazdawi — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
@jadeallenx, how do you wanna proceed release-wise?

Release a new version, from main, before this pr is merged, and then maybe release a `4.x-rc1` `kerl` after it?

Or something else?
(I'm not sure how established the API we're consuming is, at the moment).

**Comment by jadeallenx** [comment]
Probably should do as you suggest - it's been a minute since we did a release and it'd be best to cut one before otp 27 gets merged in

**Comment by paulo-ferraz-oliveira** [comment]
All actions are being re-run for 27.0-rc2, where applicable.

**Comment by paulo-ferraz-oliveira** [comment]
OTP 27 is out 🎉 I'm re-running CI and if all goes well, I'ma pull request to release a new version.

**Pull request merged**
