### PR TITLE
Allow an underscore-prefixed alphanum suffix to the OTP version

### PR DESCRIPTION
**Pull request by sanmiguel**
This helps supporting custom forks of OTP e.g. basho/otp

### CODE REVIEW

**Comment by sanmiguel** [comment]
Fixes this problem:

```
$ kerl build R16B02_basho10 16b02basho10
/usr/local/bin/kerl: line 1209: [: 16_basho10: integer expression expected
Extracting source code
Building Erlang/OTP R16B02_basho10 (16b02basho10), please wait...
/usr/local/bin/kerl: line 469: [: 16_basho10: integer expression expected
```

**Comment by sanmiguel** [comment]
I did consider that, but I was wary of making it too open... More than happy to go with the simpler regex if we can.

BTW - 2-digit? or {1,2}-digit?

**Comment by mrallen1** [comment]
Well, I guess it should be {1,2} but... for all practical purposes we always get 2 digit OTP releases. Kerl won't build R9B anyway (will it?)

**Comment by sanmiguel** [comment]
I don't think I've ever tried anything from before about... R13? 😨

**Comment by mrallen1** [comment]
Think we should go with a simple regex and then merge this :)

**Comment by sanmiguel** [comment]
Regex simplified :)

**Comment by mrallen1** [comment]
ping

**Pull request merged**
