### PR TITLE
Force OpenSSL 1.1.1f on Ubuntu 22.04, for CI purposes

### LINKED ISSUE #440: CI Ubuntu 22.04 failing because of OpenSSL 3
See [this failure][1] - not sure how to fix this but on this OS platform, we need to force install OpenSSL 1.1

[1]: https://github.com/kerl/kerl/actions/runs/4733114637/jobs/8400171586#step:6:5424

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Fixes #440.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Assuming that the fix only impacts CI OTP 23, on ubuntu-22.04 (which is now ✅), I'm moving this to **Ready for review**.

**Comment by paulo-ferraz-oliveira** [comment]
@jadeallenx, wanna give this one a looksy before we merge? (still running, but high hopes it won't fail 😄)

**Review by jadeallenx — APPROVED** [review]
Wish there was a way to be less specific about the debs to download but this works!

**Comment by jadeallenx** [comment]
Yay! Awesome sauce

**Comment by paulo-ferraz-oliveira** [comment]
It worked... for a while at least 😄

**Comment by jadeallenx** [comment]
:cry:

**Comment by paulo-ferraz-oliveira** [comment]
The remote file names changed. I'm not aware of our DEB repos work. Maybe that's normal. I'm trying to find an alternative solution and have a draft PR up, but it'll still go through the DEB repos (only less specifically).

**Pull request merged**
