### PR TITLE
Use version sorting for git backend

### PR DESCRIPTION
**Pull request by g-andrade**
This should prevent issues like `20.3.8.20` being listed before `20.3.8.3`.

The proposed solution is a best effort as `sort -V` is not universally available; it will fall back to numerical sorting if necessary (i.e. `sort -n` with locale specific rules disabled.)

The regular expression substitutions had to tweaked somewhat to make this work. The new regular expressions will:
- for lines starting with `R`, match the one or more non-space characters that follow it and prepend the captured string as `:prefix ` (note the whitespace)
- for lines starting with anything but `:`, it will match one or more non-space characters and prepend the captured string as `:prefix ` (...)

This should result in all properly formatted formatted tags being prefixed by their version strings and a whitespace.

The transformed list will then be sorted and the prefixes filtered out, similarly to how it's done for the website releases.

### CODE REVIEW

**Comment by fenollp** [comment]
I'm not sure about trimming prefixes. 
Once removed the resulting releases are then not all usable as REL in `kerl build REL`, right?

**Comment by g-andrade** [comment]
In what way? The resulting list should contain the exact same tags as before, only in a different order - unless I got something wrong.

Perhaps my description was confusing (regexes confuse me in general) - the stripped prefixes are the ones generated earlier by the regular expressions, as they allow more control over the final order, just like the website listing.

The intermediate list, before sorting and prefix stripping, is formatted like this:
```
:13B03 R13B03
:13B04 R13B04
[...]
:22.0.7 22.0.7
```

We then strip out the prefixes and recover the original list:
```
R13B03
R13B04
[...]
22.0.7
```

Won't this work in an way that's equivalent to before?

**Comment by g-andrade** [comment]
Here's the output of `kerl update releases` with the changes applied (after clearing the cache in `~/.kerl`):
[kerl-release-list.txt](https://github.com/kerl/kerl/files/3423507/kerl-release-list.txt)

**Comment by fenollp** [comment]
This looks quite correct indeed. My bad, I misunderstood the prefixes part.

I do see differences on OSX though:
```
The available releases are:							The available releases are:
R13B03										R13B03
R13B04										R13B04
R14A										R14A
									  >	R14B
R14B01										R14B01
R14B02										R14B02
R14B03										R14B03
R14B04										R14B04
R14B									  <
R15A										R15A
									  >	R15B
R15B01										R15B01
R15B02										R15B02
R15B03										R15B03
R15B03-1									R15B03-1
R15B									  <
R16A_RELEASE_CANDIDATE								R16A_RELEASE_CANDIDATE
									  >	R16B
R16B01										R16B01
R16B01_RC1									R16B01_RC1
R16B02										R16B02
R16B03										R16B03
R16B03-1									R16B03-1
R16B03_yielding_binary_to_term							R16B03_yielding_binary_to_term
R16B									  <
17.0										17.0
17.0-rc1									17.0-rc1
17.0-rc2									17.0-rc2
17.0.1										17.0.1
17.0.2										17.0.2
17.1										17.1
17.1.1										17.1.1
17.1.2										17.1.2
17.2										17.2
17.2.1										17.2.1
17.2.2										17.2.2
17.3										17.3
17.3.1										17.3.1
17.3.2										17.3.2
17.3.3										17.3.3
17.3.4										17.3.4
17.4										17.4
17.4.1										17.4.1
17.5										17.5
17.5.1										17.5.1
17.5.2										17.5.2
17.5.3										17.5.3
17.5.4										17.5.4
17.5.5										17.5.5
17.5.6										17.5.6
17.5.6.1									17.5.6.1
									  >	17.5.6.10
17.5.6.2									17.5.6.2
17.5.6.3									17.5.6.3
17.5.6.4									17.5.6.4
17.5.6.5									17.5.6.5
17.5.6.6									17.5.6.6
17.5.6.7									17.5.6.7
17.5.6.8									17.5.6.8
17.5.6.9									17.5.6.9
17.5.6.10								  <
18.0										18.0
18.0-rc1									18.0-rc1
18.0-rc2									18.0-rc2
18.0.1										18.0.1
18.0.2										18.0.2
18.0.3										18.0.3
18.1										18.1
18.1.1										18.1.1
18.1.2										18.1.2
18.1.3										18.1.3
18.1.4										18.1.4
18.1.5										18.1.5
18.2										18.2
18.2.1										18.2.1
18.2.2										18.2.2
18.2.3										18.2.3
18.2.4										18.2.4
18.2.4.0.1									18.2.4.0.1
18.2.4.1									18.2.4.1
18.3										18.3
18.3.1										18.3.1
18.3.2										18.3.2
18.3.3										18.3.3
18.3.4										18.3.4
18.3.4.1									18.3.4.1
18.3.4.1.1									18.3.4.1.1
									  >	18.3.4.10
									  >	18.3.4.11
18.3.4.2									18.3.4.2
18.3.4.3									18.3.4.3
18.3.4.4									18.3.4.4
18.3.4.5									18.3.4.5
18.3.4.6									18.3.4.6
18.3.4.7									18.3.4.7
18.3.4.8									18.3.4.8
18.3.4.9									18.3.4.9
18.3.4.10								  <
18.3.4.11								  <
19.0										19.0
19.0-rc1									19.0-rc1
19.0-rc2									19.0-rc2
19.0.1										19.0.1
19.0.2										19.0.2
19.0.3										19.0.3
19.0.4										19.0.4
19.0.5										19.0.5
19.0.6										19.0.6
19.0.7										19.0.7
19.1										19.1
19.1.1										19.1.1
19.1.2										19.1.2
19.1.3										19.1.3
19.1.4										19.1.4
19.1.5										19.1.5
19.1.6										19.1.6
19.1.6.1									19.1.6.1
19.2										19.2
19.2.1										19.2.1
19.2.2										19.2.2
19.2.3										19.2.3
19.2.3.1									19.2.3.1
19.3										19.3
19.3.1										19.3.1
19.3.2										19.3.2
19.3.3										19.3.3
19.3.4										19.3.4
19.3.5										19.3.5
19.3.6										19.3.6
19.3.6.1									19.3.6.1
									  >	19.3.6.10
									  >	19.3.6.11
									  >	19.3.6.12
									  >	19.3.6.13
19.3.6.2									19.3.6.2
19.3.6.3									19.3.6.3
19.3.6.4									19.3.6.4
19.3.6.5									19.3.6.5
19.3.6.6									19.3.6.6
19.3.6.7									19.3.6.7
19.3.6.8									19.3.6.8
19.3.6.9									19.3.6.9
19.3.6.10								  <
19.3.6.11								  <
19.3.6.12								  <
19.3.6.13								  <
20.0										20.0
20.0-rc1									20.0-rc1
20.0-rc2									20.0-rc2
20.0.1										20.0.1
20.0.2										20.0.2
20.0.3										20.0.3
20.0.4										20.0.4
20.0.5										20.0.5
20.1										20.1
20.1.1										20.1.1
20.1.2										20.1.2
20.1.3										20.1.3
20.1.4										20.1.4
20.1.5										20.1.5
20.1.6										20.1.6
20.1.7										20.1.7
20.1.7.1									20.1.7.1
20.2										20.2
20.2.0.1									20.2.0.1
20.2.1										20.2.1
20.2.2										20.2.2
20.2.3										20.2.3
20.2.4										20.2.4
20.3										20.3
20.3.1										20.3.1
20.3.2										20.3.2
20.3.2.1									20.3.2.1
20.3.3										20.3.3
20.3.4										20.3.4
20.3.5										20.3.5
20.3.6										20.3.6
20.3.7										20.3.7
20.3.8										20.3.8
20.3.8.1									20.3.8.1
20.3.8.2								  <
20.3.8.3								  <
20.3.8.4								  <
20.3.8.5								  <
20.3.8.6								  <
20.3.8.7								  <
20.3.8.8								  <
20.3.8.9								  <
20.3.8.10									20.3.8.10
20.3.8.11									20.3.8.11
20.3.8.12									20.3.8.12
20.3.8.13									20.3.8.13
20.3.8.14									20.3.8.14
20.3.8.15									20.3.8.15
20.3.8.16									20.3.8.16
20.3.8.17									20.3.8.17
20.3.8.18									20.3.8.18
20.3.8.19									20.3.8.19
									  >	20.3.8.2
20.3.8.20									20.3.8.20
20.3.8.21									20.3.8.21
20.3.8.22									20.3.8.22
									  >	20.3.8.3
									  >	20.3.8.4
									  >	20.3.8.5
									  >	20.3.8.6
									  >	20.3.8.7
									  >	20.3.8.8
									  >	20.3.8.9
21.0										21.0
21.0-rc1									21.0-rc1
21.0-rc2									21.0-rc2
21.0.1										21.0.1
21.0.2										21.0.2
21.0.3										21.0.3
21.0.4										21.0.4
21.0.5										21.0.5
21.0.6										21.0.6
21.0.7										21.0.7
21.0.8										21.0.8
21.0.9										21.0.9
21.1										21.1
21.1.1										21.1.1
21.1.2										21.1.2
21.1.3										21.1.3
21.1.4										21.1.4
21.2										21.2
21.2.1										21.2.1
21.2.2										21.2.2
21.2.3										21.2.3
21.2.4										21.2.4
21.2.5										21.2.5
21.2.6										21.2.6
21.2.7										21.2.7
21.3										21.3
21.3.1										21.3.1
21.3.2										21.3.2
21.3.3										21.3.3
21.3.4										21.3.4
21.3.5										21.3.5
21.3.6										21.3.6
21.3.7										21.3.7
21.3.7.1									21.3.7.1
21.3.8										21.3.8
21.3.8.1									21.3.8.1
21.3.8.2									21.3.8.2
21.3.8.3									21.3.8.3
21.3.8.4									21.3.8.4
21.3.8.5									21.3.8.5
21.3.8.6									21.3.8.6
22.0										22.0
22.0-rc1									22.0-rc1
22.0-rc2									22.0-rc2
22.0-rc3									22.0-rc3
22.0.1										22.0.1
22.0.2										22.0.2
22.0.3										22.0.3
22.0.4										22.0.4
22.0.5										22.0.5
22.0.6										22.0.6
22.0.7										22.0.7
```
(from https://travis-ci.org/kerl/kerl/jobs/561433439)
Can we do better than `sort -n` on OSX?

Also, since you're passing `--refs`, `grep -E -o 'OTP[_-][^^{}]+` should be removable.

Also, you `sed` calls should probably use `$SED_OPT` (although this doesn't appear to be an issue on TravisCI's OSX VMs...)

Also, instead of multiple calls to `sed`, create sequences of expressions with `sed expr1;expr2;expr3`.

BTW some `sed` expressions may just be replacable by a `cut`:
```
git ls-remote --tags --refs "$OTP_GITHUB_URL" | cut -c56-
```

Finally, please take a look at https://stackoverflow.com/a/48014434

**Comment by g-andrade** [comment]
> Finally, please take a look at git ls-remote --tags --refs --sort v:refname: https://stackoverflow.com/a/48014434

That would be perfect, but it appears to be a recent feature - my GNU/Linux installation, even though quite recent (based on Ubuntu 18.04), doesn't yet support it.

**Comment by g-andrade** [comment]
> Can we do better than sort -n on OSX?

I don't think we can. Not without either A) introducing new dependencies, B) falling back to other non-universal tools, or C) leveraging a world-class sed voodoo state machine so complex it will become self-aware.

> Also, since you're passing --refs, grep -E -o 'OTP[_-][^^{}]+ should be removable.

Removed.

> Also, you sed calls should probably use $SED_OPT (although this doesn't appear to be an issue on TravisCI's OSX VMs...)

Fixed.

> Also, instead of multiple calls to sed, create sequences of expressions with sed expr1;expr2;expr3.

I couldn't find a decent way of formatting the expressions that way. Instead, I declared them over multiple lines (as different occurrences of the `-e` argument.) Is that OK?

> BTW some sed expressions may just be replacable by a cut

Fixed.

**Comment by g-andrade** [comment]
> I don't think we can. Not without either A) introducing new dependencies, B) falling back to other non-universal tools, or C) leveraging a world-class sed voodoo state machine so complex it will become self-aware.

I went ahead and did my best at a sed script which allows us to sort versions appropriately using only `sort -n`. It works, but it's very unwieldy and distasteful.

**Comment by rjcoelho** [comment]
> > Finally, please take a look at git ls-remote --tags --refs --sort v:refname: https://stackoverflow.com/a/48014434
> 
> That would be perfect, but it appears to be a recent feature - my GNU/Linux installation, even though quite recent (based on Ubuntu 18.04), doesn't yet support it.

Apparently its available since Git 2.0 (June 2014), with more options in resent git releases. See
https://stackoverflow.com/questions/14273531/how-to-sort-git-tags-by-version-string-order-of-form-rc-x-y-z-w

**Comment by fenollp** [comment]
> > > Finally, please take a look at git ls-remote --tags --refs --sort v:refname: [stackoverflow.com/a/48014434](https://stackoverflow.com/a/48014434)
> > 
> > 
> > That would be perfect, but it appears to be a recent feature - my GNU/Linux installation, even though quite recent (based on Ubuntu 18.04), doesn't yet support it.
> 
> Apparently its available since Git 2.0 (June 2014), with more options in resent git releases. See
> [stackoverflow.com/questions/14273531/how-to-sort-git-tags-by-version-string-order-of-form-rc-x-y-z-w](https://stackoverflow.com/questions/14273531/how-to-sort-git-tags-by-version-string-order-of-form-rc-x-y-z-w)

Well on Debian 9 (Stretch, 2017) `git ls-remote` doesn't have `--sort` so yeah I think in about a hundred years we'll be able to rely on this.

**Comment by fenollp** [comment]
Haha this `sed` call of the dead is looking awful! If it does the job I'm down with it and from the CI it does seem to do the job. Note however that this is write-once code to me and if it needs fixing & I'm the only one around I might just rewrite this haha (hopefully that won't happen).

@mrallen1 It looks like CircleCI isn't enabled for Pull Requests from forked repos. Can you try this?:
> Build Settings > Advanced Settings and enable the Build forked pull requests option

from https://circleci.com/blog/managing-secrets-when-you-have-pull-requests-from-outside-contributors/

**Comment by g-andrade** [comment]
> Haha this sed call of the dead is looking awful! If it does the job I'm down with it and from the CI it does seem to do the job. Note however that this is write-once code to me and if it needs fixing & I'm the only one around I might just rewrite this haha (hopefully that won't happen).

It really is awful. I'll try and maybe add some comments and more descriptive names to the loops, or otherwise in one month not even I will understand what I wrote.

**Comment by g-andrade** [comment]
I added some comments to the sed transform; hopefully it's more maintainable now.

**Comment by g-andrade** [comment]
I've fixed some quirks which I hadn't noticed following the previous push.

**Comment by eproxus** [comment]
Any chance this could get tagged in a new release version of Kerl?

As a side note, would `sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n` have worked? I can use it as this and get proper sorting:

```
cat $KERL_BASE_DIR/otp_releases | sort -R | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n
```

**Pull request merged**
