### PR TITLE
fix: Probe failed for libncurses5-dev

### LINKED ISSUE #518: Ubuntu 24.04: kerl generates a warning for non-existing libncurses5-dev package
#### The bug

kerl generates a warning for not having libncurses5-dev for Ubuntu, which is not in the apt library of Ubuntu 24.04

#### Software versions

* Operating System: Ubuntu 24.04 (not LTS yet, development version as of 12-APR-2024)
* Erlang/OTP: 26.2.3
* `kerl`: 4.1.0

#### How to replicate

Running a script of `otp-install-from-git-ubuntu.sh 26.2.3`

otp-install-from-git-ubuntu.sh source:

```sh
#!/bin/sh
# For Ubuntu with a local OpenSSL
OTP_VERSION=$1
OPENSSL_LOCAL="/opt/openssl/3.2.1"
INSTALL_DIR_PREFIX="/home/kenji/otp/"
INSTALL_NAME=${OTP_VERSION}
#
env \
    CC=/usr/bin/cc \
    CXX=/usr/bin/c++ \
    CFLAGS="-O3 -fstack-protector-strong" LDFLAGS="-fstack-protector-strong" \
    MAKEFLAGS="-j8" \
    KERL_BUILD_DOCS="yes" \
    KERL_DOC_TARGETS="chunks" \
    KERL_BUILD_PLT="yes" \
    KERL_CONFIGURE_OPTIONS="--disable-dynamic-ssl-lib --enable-kernel-poll --enable-dirty-schedulers --disable-sctp --disable-sharing-preserving --without-javac --without-odbc --with-ssl=${OPENSSL_LOCAL} --with-wx-config=/opt/wx-3.2/bin/wx-config" \
    sh -c "(kerl build git https://github.com/jj1bdx/otp/ OTP-${OTP_VERSION} ${INSTALL_NAME} && kerl install ${INSTALL_NAME} ${INSTALL_DIR_PREFIX}${INSTALL_NAME})"
```

#### Expected behaviour

kerl generates the following WARNING message:

```
Checking out Erlang/OTP git repository from https://github.com/jj1bdx/otp/...
Building (git) Erlang/OTP OTP-26.2.3; please wait...
Initializing (build) log file at /home/kenji/.kerl/builds/26.2.3/otp_build_git.log.
WARNING: [packages] Probe failed for libncurses5-dev (distro: ubuntu): probe "dpkg-query -Wf'${db:Status-abbrev}' "libncurses5-dev" 2>/dev/null | \grep -q '^i'" returned 1
```

#### Additional context

Installed libncurses-related packages searched by `sudo apt list | grep libncurses`:

```
libncurses-dev/noble,now 6.4+20240113-1ubuntu1 amd64 [installed]
libncurses5/now 6.3-2ubuntu0.1 amd64 [installed,local]
libncurses6/noble,now 6.4+20240113-1ubuntu1 amd64 [installed]
libncursesada-dev/noble 6.3.20211021-11build1 amd64
libncursesada6.2.4/noble 6.3.20211021-11build1 amd64
libncursesw5/now 6.3-2ubuntu0.1 amd64 [installed,local]
libncursesw6/noble,now 6.4+20240113-1ubuntu1 amd64 [installed]
```

I think for Ubuntu 24.04 kerl should accept libncurses-dev instead of libncurses5-dev (not in the apt list anymore).

### PR DESCRIPTION
**Pull request by 03juan**
# Description

Relax the probe for libncurses package in Debian-based distros.

Closes #518.

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/kerl/kerl/blob/main/CONTRIBUTING.md)

## Local testing

_All commands run with up-to-date apt sources._

<details open><summary>Debian 12 (bookworm) with <code>libncurses5-dev</code> installed</summary>

```sh
$ dpkg-query -l 'libncurses[^w]*dev'
...header...
ii  libncurses-dev:amd64  6.4-4        amd64        developer\'s libraries for ncurses
ii  libncurses5-dev:amd64 6.4-4        amd64        transitional package for libncurses-dev

$ dpkg-query -Wf='${db:Status-abbrev}' "libncurses[^w]*dev"
ii ii

$ ./kerl build 26.2.5
Downloading (from GitHub) Erlang/OTP 26.2.5 to /home/juan/.kerl/archives...
Extracting source code for normal build...
Building (normal) Erlang/OTP 26.2.5 (26.2.5); please wait...
Initializing (build) log file at /home/juan/.kerl/builds/26.2.5/otp_build_26.2.5.log.
^C

$ head -13 /home/juan/.kerl/builds/26.2.5/otp_build_26.2.5.log
*** Sun May  5 03:41:26 PM SAST 2024 - kerl build 26.2.5 ***
Build options:
*
[packages] Found Debian GNU/Linux 12 (bookworm) with ID debian
[packages] Release ID found in /etc/os-release: debian
[packages] Found package declarations for your Linux distro: debian
[packages] Probe success for automake (distro: debian)!
[packages] Probe success for autoconf (distro: debian)!
[packages] Probe success for gcc (distro: debian)!
[packages] Probe success for make (distro: debian)!
[packages] Probe success for libssl-dev (distro: debian)!
[packages] Probe success for libncurses[^w]*dev (distro: debian)!
[packages] Probe success for g++ (distro: debian)!
```

</details> 

<details open><summary>Ubuntu 22.04 (jammy) with <code>libncurses5-dev</code> installed</summary>

```sh
$ dpkg-query -l 'libncurses[^w]*dev'
...header...
ii  libncurses-dev:amd64  6.3-2ubuntu0.1 amd64        developer\'s libraries for ncurses
ii  libncurses5-dev:amd64 6.3-2ubuntu0.1 amd64        transitional package for libncurses-dev

$ dpkg-query -Wf='${db:Status-abbrev}' "libncurses[^w]*dev"
ii ii

$ ./kerl build 26.2.5
Downloading (from GitHub) Erlang/OTP 26.2.5 to /home/juan/.kerl/archives...
Extracting source code for normal build...
Building (normal) Erlang/OTP 26.2.5 (26.2.5); please wait...
Initializing (build) log file at /home/juan/.kerl/builds/26.2.5/otp_build_26.2.5.log.
^C

$ head -13 /home/juan/.kerl/builds/26.2.5/otp_build_26.2.5.log
*** Sun May  5 15:49:00 SAST 2024 - kerl build 26.2.5 ***
Build options:
*
[packages] Found Ubuntu 22.04.4 LTS with ID ubuntu
[packages] Release ID found in /etc/os-release: ubuntu
[packages] Found package declarations for your Linux distro: ubuntu
[packages] Probe success for automake (distro: ubuntu)!
[packages] Probe success for autoconf (distro: ubuntu)!
[packages] Probe success for gcc (distro: ubuntu)!
[packages] Probe success for make (distro: ubuntu)!
[packages] Probe success for libssl-dev (distro: ubuntu)!
[packages] Probe success for libncurses[^w]*dev (distro: ubuntu)!
[packages] Probe success for g++ (distro: ubuntu)!
```

</details>

<details open><summary>Ubuntu 24.04 (noble) with <code>libncurses-dev</code> installed</summary>

```sh
$ dpkg-query -l 'libncurses[^w]*dev'
...header...
ii  libncurses-dev:amd64 6.4+20240113-1ubuntu2 amd64        developer\'s libraries for ncurses
un  libncurses5-dev      <none>                <none>       (no description available)

$ dpkg-query -Wf='${db:Status-abbrev}' "libncurses[^w]*dev" 
ii un

$ ./kerl build 26.2.5       
Downloading (from GitHub) Erlang/OTP 26.2.5 to /home/juan/.kerl/archives...
Extracting source code for normal build...
Building (normal) Erlang/OTP 26.2.5 (26.2.5); please wait...
Initializing (build) log file at /home/juan/.kerl/builds/26.2.5/otp_build_26.2.5.log.
^C

$ head -13 /home/juan/.kerl/builds/26.2.5/otp_build_26.2.5.log 
*** Sun May  5 15:34:23 SAST 2024 - kerl build 26.2.5 ***
Build options:
* 
[packages] Found Ubuntu 24.04 LTS with ID ubuntu
[packages] Release ID found in /etc/os-release: ubuntu
[packages] Found package declarations for your Linux distro: ubuntu
[packages] Probe success for automake (distro: ubuntu)!
[packages] Probe success for autoconf (distro: ubuntu)!
[packages] Probe success for gcc (distro: ubuntu)!
[packages] Probe success for make (distro: ubuntu)!
[packages] Probe success for libssl-dev (distro: ubuntu)!
[packages] Probe success for libncurses[^w]*dev (distro: ubuntu)!
[packages] Probe success for g++ (distro: ubuntu)!
```

</details>

### CODE REVIEW

**Comment by 03juan** [comment]
By the way, what is the philosophy around preferring the wildcard probe instead of outright requiring `libncurses-dev`?

According to the [`ncurses_6.4+20240113-1ubuntu2` changelog](https://changelogs.ubuntu.com/changelogs/pool/main/n/ncurses/ncurses_6.4+20240113-1ubuntu2/changelog) the `libncurses5-dev` package has been a transitional package since 2018

>ncurses (6.1+20180210-1) experimental; urgency=low
>
>  * Switch to the ncurses 6 ABI (Closes: #230990), but continue to ship
>    ABI 5 shared library packages for now.
>  * Change the section of the ABI 5 library packages to oldlibs and update
>    their descriptions accordingly.
>  * Merge lib{tinfo,ncurses5,ncursesw5}-dev into a new libncurses-dev
>    package and turn them into transitional packages (Closes: #840429).
>    Add a lintian override for the resulting duplicate-short-description
>    notices.
>  * Merge the multilib -dev packages into single lib{32,64}ncurses-dev
>    packages which have Conflicts/Replaces/Provides on the old ones.
>
> -- Sven Joachim <svenjoac@gmx.de>  Thu, 22 Feb 2018 20:23:16 +0100

and going forward it's no longer being built.

>ncurses (6.4+20230603-1) experimental; urgency=low
> 
>   * Stop building the empty transitional packages libtinfo-dev
>     and libncurses{,w}5-dev (Closes: #1032708, #1032740, #1032741).
> 
>  -- Sven Joachim <svenjoac@gmx.de>  Thu, 15 Jun 2023 18:34:20 +0200

**Comment by paulo-ferraz-oliveira** [comment]
> what is the philosophy

I don't think there's a philosophy 😄. I didn't invest much time understanding how that lib was renamed/deprecated/updated.

I'd say, though, that if the name is gonna change we can adapt to the new one, even if that means that older installations might complain about it (if I'm not mistaken installation doesn't stop, this is just a warning).

**Comment by 03juan** [comment]
Haha fair enough. Well this works well enough so up to you if you want to leave as is. Maybe at least we can note the OS package change in the readme?

**Comment by paulo-ferraz-oliveira** [comment]
I'm Ok to keep as-is (your current pr), in any case (i.e. if tests pass I'm merging). And no need to change the README; this probe stuff is a best-effort, not a strong rule 😄. More info in the README, [here](https://github.com/kerl/kerl?tab=readme-ov-file#kerl_check_build_packages).

**Comment by paulo-ferraz-oliveira** [comment]
Merged. Thanks for the pr.

**Pull request merged**
