### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by maierru**

### CODE REVIEW

**Comment by mrallen1** [comment]
Thanks for the update. Can you help me understand how OpenSSL was installed in the location in this PR?  Via homebrew? Or did you manually install openssl there yourself?

**Comment by maierru** [comment]
Actually, I don't remember, but I think it was homebrew.

**Comment by mrallen1** [comment]
Any update on this?

**Comment by mrallen1** [comment]
Hey thanks for the PR but I'm going to close this. I think our README handles this situation adequately.

**Pull request closed without merging**
