### PR TITLE
Bypass version check when building on MacOS Monterey

### PR DESCRIPTION
**Pull request by Agilulfo**
Fixes: #394

Build of some older version of Erlang fails on MacOS Montery (12)

A similar issue was affecting MacOS Big Sur 
I've changed the kerl script to apply the same solution currently implemented for Big Sur

I've tested the solution as follow:

```
➜  kerl git:(master) ./kerl build 22.3
Downloading 22.3 to /Users/flavio/.kerl/archives...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   652  100   652    0     0   4571      0 --:--:-- --:--:-- --:--:--  4759
100 83.8M  100 83.8M    0     0  18.6M      0  0:00:04  0:00:04 --:--:-- 20.4M
Extracting source code
Building Erlang/OTP 22.3 (22.3), please wait...
Build failed.

  You are natively building Erlang/OTP for a later version of MacOSX
  than current version (12.1). You either need to
  cross-build Erlang/OTP, or set the environment variable
  MACOSX_DEPLOYMENT_TARGET to 12.1 (or a lower version).


ERROR: /Users/flavio/.kerl/builds/22.3/otp_src_22.3/make/configure failed!
make: *** No rule to make target `is_cross_configured'.  Stop.
make: *** No rule to make target `all'.  Stop.

Please see /Users/flavio/.kerl/builds/22.3/otp_build_22.3.log for full details.
➜  kerl git:(master) git checkout patch-macos-monterey
Switched to branch 'patch-macos-monterey'
➜  kerl git:(patch-macos-monterey) ./kerl build 22.3
Extracting source code
Building Erlang/OTP 22.3 (22.3), please wait...
APPLICATIONS DISABLED (See: /Users/flavio/.kerl/builds/22.3/otp_build_22.3.log)
 * jinterface     : Java compiler disabled by user

APPLICATIONS INFORMATION (See: /Users/flavio/.kerl/builds/22.3/otp_build_22.3.log)
 * wx             : wxWidgets not found, wx will NOT be usable

DOCUMENTATION INFORMATION (See: /Users/flavio/.kerl/builds/22.3/otp_build_22.3.log)
 * documentation  :
 *                  fop is missing.
 *                  Using fakefop to generate placeholder PDF files.

Erlang/OTP 22.3 (22.3) has been successfully built
```

### CODE REVIEW

**Review by jadeallenx — APPROVED** [review]

**Comment by jadeallenx** [comment]
Thank you for the patch!

**Comment by Agilulfo** [comment]
@jadeallenx how often do you tag a new version of kerl? 
Do you have peridic releases or you simply release a new version only when it is necessary?
Do you mind if I push a PR to bump the version? (this would allow me to update asdf too)

**Comment by jadeallenx** [comment]
Usually I just do it when there's been a few PRs but I can cut a release today

**Comment by jadeallenx** [comment]
2.2.4 is tagged :)

**Pull request merged**
