### PR TITLE
Fix `kerl upgrade` example on README.md

### PR DESCRIPTION
**Pull request by Alberdi**
# Description

The text didn't match the expected (and current) script behaviour, because it was saying that the old version was still available.

Closes #&lt;issue&gt;.

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/kerl/kerl/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
👋 thanks for the pull request, but I don't think we need to update it. It's documentation, as an example (as you state); we just put that there kinda for the format.

**Comment by Alberdi** [comment]
I just wanted to point out that the format wasn't right. In case it was not clear with all the numbers changing, before the PR the text was:
```
Local kerl found (/usr/local/bin/kerl) at version $OLD_VERSION.
Remote kerl found at version $NEW_VERSION.
Versions are different. Upgrading to $NEW_VERSION...
kerl $OLD_VERSION is now available at /usr/local/bin/kerl.
```

So I've changed that last line in the example to reference `$NEW_VERSION` instead, as the `kerl` script properly does.

Even then, it's a very minor thing.

**Comment by paulo-ferraz-oliveira** [comment]
Oh, I see.

**Comment by paulo-ferraz-oliveira** [comment]
Perfect. Thanks for this.

**Pull request merged**
