### PR TITLE
Add TravisCI badge

### PR DESCRIPTION
**Pull request by fenollp**

### CODE REVIEW

**Comment by mrallen1** [comment]
Given Travis troubles lately, been seriously thinking about moving all of the tests to circle lol

What do you think?

**Comment by fenollp** [comment]
What troubles? [I don't see anything failing](https://travis-ci.org/kerl/kerl/builds)

Nothing against it. Seems possible to [build for OSX by asking them.](https://circleci.com/pricing/#faq-section-os-x) Here's [an example of a config file for matrix builds](https://github.com/census-instrumentation/opencensus-erlang/blob/master/.circleci/config.yml) (for the record).

**Comment by mrallen1** [comment]
Just been very slow on running tests lately.  Frustrating.

**Comment by fenollp** [comment]
Yep, these osx builds from 2 days ago are still in the backlog...

**Pull request merged**
