### PR TITLE
Make Pop!_OS a `kerl`-known Linux distro, for package probing

### LINKED ISSUE #504: Warning checking build packages on Pop OS
#### The bug

When building some versions in PopOS system, it warns about the unknown system.

#### Software versions

A list of software versions where the bug is apparent, as detailed as possible:

* Operating System: Pop!_OS 22.04 LTS
* Erlang/OTP: 26.2.2
* `kerl`: 4.0.0
* other (where applicable): (maybe all versions due to its an OS system issue)

#### How to replicate

An ordered list of steps to replicate the bug, e.g.:

1. run `kerl build 26.2.2 erlang_26.2.2`
2. search for `[packages] Unknown Linux distro pop; not checking build packages.` in the error output

#### Expected behaviour

Should not warn about the os and successfully validates the required build packages.

#### Additional context
image

BTW, thanks for all the work!

### PR DESCRIPTION
**Pull request by aschiavon91**
# Description

Adding support to PopOS build package validation, closes #504 

Closes #&lt;issue&gt;.

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/kerl/kerl/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
👋 @aschiavon91. I'm gonna try to find a suitable container to run this with (I don't personally use Pop!_OS) and get back to this later. Thanks for the pull request, it's as simple as it's supposed to be.

**Comment by paulo-ferraz-oliveira** [comment]
I updated the pr title so when the release notes are generated this is not apparent as a bug fix, which it's not 😄

**Comment by paulo-ferraz-oliveira** [comment]
CI's Ok with this one. Thanks for the pr.

**Comment by aschiavon91** [comment]
Hey @paulo-ferraz-oliveira thanks for the fast review, and sorry for my mistake labeling as a bug.

**Comment by paulo-ferraz-oliveira** [comment]
No prob. I was just mentioning for future reference, since there's other distros `kerl` doesn't know about either 😄

**Pull request merged**
