### PR TITLE
Print the list of releases/updates with the command column

### PR DESCRIPTION
**Pull request by nihilismus**
Currently:

$ kerl list releases
R10B-0 R10B-10 R10B-1a R10B-2 R10B-3 R10B-4 ...
13B04 R13B R14A R14B01 R14B02 R14B03 R14B04 ...

With these changes:

$ kerl list releases
The available releases are:
R10B-0                                  R14B01
R10B-10                                 R14B02
R10B-1a                                 R14B03
...
R13B                                    18.3
R14A

### CODE REVIEW

**Comment by mrallen1** [comment]
Thanks for the patch! I like the idea. The default ought to be the "spaces" option, so any automation built around this command won't break.  

So `kerl list releases` should work as it always has, and if you give `kerl list releases columns` it will format the list through the `column` command.

**Comment by nihilismus** [comment]
@mrallen1 I added `kerl list releases columns` and `kerl update releases columns`, what do you think?

**Comment by mrallen1** [comment]
@nihilismus thanks for the patch - I think we're interested in making

`kerl list releases` directly use `column` - we will just drop the column and spaces commands.  That should simplify this patch and make the output look nicer.

**Comment by mrallen1** [comment]
@nihilismus ping - are you interested in making the suggested change?

**Comment by mrallen1** [comment]
Thanks for the contribution, but I'm going to go ahead and close this PR now. Please reopen it if you're still interested.

**Pull request closed without merging**
