### PR TITLE
Fix Issue #53

### PR DESCRIPTION
**Pull request by mazenharake**
Show configuration warnings after running configuration

### CODE REVIEW

**Comment by mrallen1** [comment]
Thanks for the contribution. I will test this soon!

**Comment by mazenharake** [comment]
Didn't realize my next commit would show up here as well but anyway, the second commit allows for customization of the prompt and has nothing to do with the fix for 53. I don't know if that is a useful feature but I thought I'd add it anyway. 

Let me know if I need to separate them in the pull request somehow if you can't take just one of the commits.

**Comment by mrallen1** [comment]
OS X/FreeBSD doesn't support `head -n -2` like GNU head in Linux.

```
APPLICATIONS DISABLED (See: /Users/mallen/.kerl/builds/test13/otp_build_19.0.2.log)
head: illegal line count -- -2

head: illegal line count -- -2
APPLICATIONS INFORMATION (See: /Users/mallen/.kerl/builds/test13/otp_build_19.0.2.log)

head: illegal line count -- -2
DOCUMENTATION INFORMATION (See: /Users/mallen/.kerl/builds/test13/otp_build_19.0.2.log)
```

**Comment by mrallen1** [comment]
This is the output when I replaced `head -n -2` with `head -n 2`

```
APPLICATIONS DISABLED (See: /Users/mallen/.kerl/builds/test13/otp_build_19.0.2.log)
 * odbc           : ODBC library - link check failed
 * 

APPLICATIONS INFORMATION (See: /Users/mallen/.kerl/builds/test13/otp_build_19.0.2.log)
 * wx             : wxWidgets not found, wx will NOT be usable
 * 

DOCUMENTATION INFORMATION (See: /Users/mallen/.kerl/builds/test13/otp_build_19.0.2.log)
 * documentation  : 
 *                  fop is missing.
```

Looks pretty good to me!

**Comment by mazenharake** [comment]
I see. looking at it now, I'll try to use sed instead or look at how head behaves in FreeBSD

**Comment by mazenharake** [comment]
Yes, `head -n 2` only outputs the first two lines as expected while in gnu head the "minus" means to skip those lines.

**Comment by mazenharake** [comment]
I've isolated the change in its own branch and commit. Opened a new pull request here: https://github.com/kerl/kerl/pull/148 , it removes the head command and uses awk to filter the unwanted lines

**Pull request closed without merging**
