### PR TITLE
circleci: add another CI provider for R15 builds

### PR DESCRIPTION
**Pull request by fenollp**
Follow up of discussion at https://github.com/kerl/kerl/pull/242
CircleCI is very similar to TravisCI in how simple it is to set up & how it is free for open source projects.

Build fails for some reason: https://circleci.com/gh/fenollp/kerl/17
Ideas?

PS: I'll squash when ready.

### CODE REVIEW

**Comment by fenollp** [comment]
So now circleci fails to run R15B03-1 due to crypto app not being included. https://circleci.com/gh/fenollp/kerl/19
This is exactly as described in https://github.com/kerl/kerl/issues/226

Now that debian (et al.) repos have a libssl that's too new for old Erlangs I wonder if there's even a way to build a working R15. One can downgrade libssl but package managers may upgrade it themselves later...
Maybe there's a way to install multiple libssls side by side? Maybe some libssl fork exists that is packaged in most distros happen to work with R15's build system? Last resort is building libssl from source, which might not be an issue for people that willing to run R15 anyway.

BTW I would vote to change the default behavior to fail ./configure if crypto app won't be built (instead of just showing a warning).
I would argue that very few people don't want crypto but then again probably not many want R15.
A warning is easily missed. A flag like `--dont-panic-if-no-libssl` can be added for the previous behavior.
This is kinda related to https://github.com/kerl/kerl/issues/237

**Comment by mrallen1** [comment]
Where's this at now? :) Thanks.

**Comment by fenollp** [comment]
This is ready. You can see the results at https://circleci.com/gh/fenollp/kerl

**Comment by fenollp** [comment]
https://circleci.com/gh/kerl/kerl needs to be activated & maybe the README could show a badge for both CIs?

**Comment by mrallen1** [comment]
think i activated it - a build is running anyway.  Where do you get a badge from?

**Comment by mrallen1** [comment]
OK, got it.

**Pull request merged**
