### PR TITLE
Build (only) chunks on OTP 23+

### PR DESCRIPTION
**Pull request by mrallen1**
Problem to solve: #334 

Solution:
* Introduce a new environment variable to control which doc components get built on OTP 23+
* Do not artificially nest documentation a layer deeper than necessary

### CODE REVIEW

**Comment by mrallen1** [comment]
There's still some kind of problem because I see this o/p:
```shell
mallen@SNOW:~$ cd ~/erlangs/23.0-rc2/
mallen@SNOW:~/erlangs/23.0-rc2$ find . -name *.chunk -print
./erlang/lib/snmp-5.6/doc/chunks/snmp_target_mib.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpa_error_logger.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpm_mpd.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_view_based_acm_mib.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_community_mib.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_user_based_sm_mib.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpm.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpa_supervisor.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpm_conf.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpa_error.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_framework_mib.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpa.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_pdus.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpa_error_io.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_generic.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpa_conf.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpa_local_db.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_standard_mib.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_index.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmp_notification_mib.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpc.chunk
./erlang/lib/snmp-5.6/doc/chunks/snmpa_mpd.chunk
...
./erlang/lib/wx-1.9.1/doc/chunks/wxScrollWinEvent.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxPaintEvent.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxShowEvent.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxAuiDockArt.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxAcceleratorTable.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxGraphicsPath.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxSystemSettings.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxMouseCaptureLostEvent.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxStatusBar.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxDialog.chunk
./erlang/lib/wx-1.9.1/doc/chunks/wxNotebook.chunk
./erlang/lib/asn1-5.0.11/doc/chunks/asn1ct.chunk
./erlang/lib/debugger-5.0/doc/chunks/i.chunk
./erlang/lib/debugger-5.0/doc/chunks/debugger.chunk
./erlang/lib/debugger-5.0/doc/chunks/int.chunk
```
But I still am seeing this in the shell
```
mallen@SNOW:~/github/kerl$ erl
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Eshell V11.0  (abort with ^G)
1> h(ssl).

        ssl

  There is no documentation for ssl
ok
```

**Comment by garazdawi** [comment]
I've pushed some fixed here: https://github.com/garazdawi/kerl/tree/docs

You are mixing doing `make release` for creating the Erlang/OTP libraries, but doing an `make install` for the docs. This ends up confusing everything. I would suggest doing a release both libraries and docs, but you can, of course, do install for both as well.

**Comment by seriyps** [comment]
How do I use this?
I've tried the following:

```
$ MAKEFLAGS="-j3" KERL_BUILD_DOCS=yes KERL_DOC_TARGETS=chunks kerl build 23.0 23.0
Downloading OTP-23.0.tar.gz to /home/seriy/.kerl/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   120  100   120    0     0    851      0 --:--:-- --:--:-- --:--:--   851
100 53.7M  100 53.7M    0     0  2604k      0  0:00:21  0:00:21 --:--:-- 6926k
Extracting source code
Building Erlang/OTP 23.0 (23.0), please wait...
WARNING: It appears that a required development package 'libncurses5-dev' is not installed.
APPLICATIONS DISABLED (See: /home/seriy/.kerl/builds/23.0/otp_build_23.0.log)
 * jinterface     : No Java compiler found
 * odbc           : ODBC library - link check failed

DOCUMENTATION INFORMATION (See: /home/seriy/.kerl/builds/23.0/otp_build_23.0.log)
 * documentation  : 
 *                  xmllint is missing.
 *                  Using fakefop to generate placeholder PDF files.

Building docs...
Erlang/OTP 23.0 (23.0) has been successfully built
$ kerl install 23.0 /home/seriy/workspace/erlang_setups/23.0
Installing Erlang/OTP 23.0 (23.0) in /home/seriy/workspace/erlang_setups/23.0...
You can activate this installation running the following command:
. /home/seriy/workspace/erlang_setups/23.0/activate
Later on, you can leave the installation typing:
kerl_deactivate
$ source /home/seriy/workspace/erlang_setups/23.0/activate
$ erl                                                                                                                                                                       [17:59:20]
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V11.0  (abort with ^G)
1> h(lists, filter, 2).

  -spec filter(Pred, List1) -> List2
                  when
                      Pred :: fun((Elem :: T) -> boolean()),
                      List1 :: [T],
                      List2 :: [T],
                      T :: term().

  There is no documentation for filter/2
```

**Comment by seriyps** [comment]
Ok, apparently, I need to add `KERL_BUILD_DOCS=yes` to `kerl install` command as well:

```
$ KERL_BUILD_DOCS=yes kerl install 23.0 /home/seriy/workspace/erlang_setups/23.0
Installing Erlang/OTP 23.0 (23.0) in /home/seriy/workspace/erlang_setups/23.0...
You can activate this installation running the following command:
. /home/seriy/workspace/erlang_setups/23.0/activate
Later on, you can leave the installation typing:
kerl_deactivate
$ source /home/seriy/workspace/erlang_setups/23.0/activate
$ erl
Erlang/OTP 23 [erts-11.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Eshell V11.0  (abort with ^G)
1> h(lists, filter, 2).

  -spec filter(Pred, List1) -> List2
                  when
                      Pred :: fun((Elem :: T) -> boolean()),
                      List1 :: [T],
                      List2 :: [T],
                      T :: term().

  List2 is a list of all elements Elem in List1 for which Pred(Elem) returns true.
ok
2> 
```

In context of installation variable name `KERL_BUILD_DOCS` looks confusing imo

**Pull request merged**
