### PR TITLE
Fix fish shell (de)activate

### PR DESCRIPTION
**Pull request by x0id**
# Description

The fish shell kerl activate/deactivate code has been improved and refactored to fix environment setup/cleanup issues (#458).

The test suite for fish shell based activate/deactivate has been added.

This PR partially (for the fish shell) resolves issue #458.

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/kerl/kerl/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
👍 very nice, @x0id, thanks.

I don't know enough `fish` to do a proper review on this, but it seems solid, especially since it's tested (if I understood correctly, similar to its `bash` counterpart).

@jadeallenx, I'm Ok to merge as is and then update/fix if there's complaints from the community. What do you say?

**Comment by paulo-ferraz-oliveira** [comment]
And, @x0id, if you think you'll get around to the rest of #458 soonish, we can probably postpone a release until then, otherwise we can release a patch now and patch later. Thoughts?

**Comment by x0id** [comment]
@paulo-ferraz-oliveira, I think there is no rush in releasing the fish shell updates, I'm not sure actually how many people use it. I plan to work on sh/csh in the next couple of weeks.

**Comment by jadeallenx** [comment]
> @jadeallenx, I'm Ok to merge as is and then update/fix if there's complaints from the community. What do you say?

I think we should merge it too.

**Comment by jadeallenx** [comment]
> I'm not sure actually how many people use it. I plan to work on sh/csh in the next couple of weeks.

Nothing makes those hidden users show up than a new release that breaks something lol 😄

**Review by jadeallenx — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
It's squash-merged. Thanks all.

**Pull request merged**
