### PR TITLE
Testing odbc+wx on OTP 20.3 on a slim jessie

### PR DESCRIPTION
**Pull request by fenollp**
This helps to show that #270 is probably not kerl's fault.

### CODE REVIEW

**Comment by fenollp** [comment]
Since the related issue was not an issue this can probably be closed. 
I can update this to tweak one of the existing tests so that the checks here (wx, odbc, ...) are done instead of adding a new one and saving some time if you guys think that can be good. That’d save us a concurrent build and maybe some runtime.

**Comment by mrallen1** [comment]
Yeah, that sounds good to me.

**Comment by fenollp** [comment]
@mrallen1 What do you think about this failure? https://circleci.com/gh/fenollp/kerl/129
I explicitly told it to skip wx but that happened only after configuration?

**Comment by mrallen1** [comment]
Don't have time to look at it right now but that seems mighty odd.

**Comment by mrallen1** [comment]
Fine to merge this whenever you think it's ready.

**Comment by fenollp** [comment]
@mrallen1 any idea if a dependency could be missing and trigger a build failure for `git` backend on ubuntu:trusty? see https://github.com/kerl/kerl/pull/271/commits/f9a36a1c45dff838479e8ceeab1f479040621817
That's kinda weird

**Comment by mrallen1** [comment]
Yeah that is super weird - what is the exact failure message?  I'm at a loss to say what the cause might be.

**Comment by fenollp** [comment]
Here's the build message. I'm running a build to get the output of the configure step.
```
export _KERL_VSN=17.0
#export KERL_BUILD_BACKEND=tarball (unset)
export KERL_CONFIGURE_DISABLE_APPLICATIONS='wx odbc'
export MAKEFLAGS="-j$(getconf _NPROCESSORS_ONLN)"
./kerl build "$_KERL_VSN" "$_KERL_VSN" | tee build.log
Downloading OTP-17.0.tar.gz to /root/.kerl/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

100   120    0   120    0     0   1185      0 --:--:-- --:--:-- --:--:--  1188

  0     0    0 31.5M    0     0  6995k      0 --:--:--  0:00:04 --:--:-- 7782k
Extracting source code
Building Erlang/OTP 17.0 (17.0), please wait...
APPLICATIONS DISABLED (See: /root/.kerl/builds/17.0/otp_build_17.0.log)
 * jinterface     : No Java compiler found
 * odbc           : odbc disabled by user.
 * odbc           : User gave --without-odbc option
 * wx             : User gave --without-wx option

APPLICATIONS INFORMATION (See: /root/.kerl/builds/17.0/otp_build_17.0.log)
 * wx             : wxWidgets not found, wx will NOT be usable

DOCUMENTATION INFORMATION (See: /root/.kerl/builds/17.0/otp_build_17.0.log)
 * documentation  : 
 *                  xsltproc is missing.
 *                  fop is missing.
 *                  xmllint is missing.
 *                  The documentation can not be built.

Build failed.
compile: warnings being treated as errors
dbg_wx_filedialog_win.erl:21: behaviour wx_object undefined
make[3]: *** [../ebin/dbg_wx_filedialog_win.beam] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory `/root/.kerl/builds/17.0/otp_src_17.0/lib/debugger/src'
make[2]: *** [opt] Error 2
make[2]: Leaving directory `/root/.kerl/builds/17.0/otp_src_17.0/lib/debugger'
make[1]: *** [opt] Error 2
make[1]: Leaving directory `/root/.kerl/builds/17.0/otp_src_17.0/lib'
make: *** [libs] Error 2

Please see /root/.kerl/builds/17.0/otp_build_17.0.log for full details.
Exited with code 1
```

**Comment by fenollp** [comment]
Yeah so something about building with git in ubuntu:trusty: https://github.com/kerl/kerl/pull/271/commits/f9a36a1c45dff838479e8ceeab1f479040621817 ...

**Pull request merged**
